# Creating a Keras model
- Specify Architecture
- Compile
- Fit
- Predict

# Applying Keras model in regression problem

In [10]:
import pandas as pd
wages =pd.read_csv('datasets/hourly_wages.csv')
wages.head()

   wage_per_hour  union  education_yrs  ...  south  manufacturing  construction
0           5.10      0              8  ...      0              1             0
1           4.95      0              9  ...      0              1             0
2           6.67      0             12  ...      0              1             0
3           4.00      0             12  ...      0              0             0
4           7.50      0             12  ...      0              0             0

[5 rows x 10 columns]

In [11]:
import numpy as np

# Initializing features and labels: predictors and target resp 
predictors = np.array(wages.drop('wage_per_hour',axis=1))
target = np.array(wages['wage_per_hour'])

In [12]:
# Train - test split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(predictors, target, 
                                                   test_size=0.3, random_state=42)

## Specifying the model

In [19]:
# Import necessary modules
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential

# Save the number of columns in predictors: n_cols
n_cols = predictors.shape[1]

# Set up the model: model
model = Sequential()

# Add the first layer
model.add(Dense(50, activation='relu', input_shape=(n_cols,)))

# Add the second layer
model.add(Dense(32, activation='relu'))

# Add the output layer
model.add(Dense(1))

In [20]:
# Model summary
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_6 (Dense)             (None, 50)                500

 dense_7 (Dense)             (None, 32)                1632

 dense_8 (Dense)             (None, 1)                 33

=================================================================
Total params: 2,165
Trainable params: 2,165
Non-trainable params: 0
_________________________________________________________________

## Compiling and Fitting the model

In [21]:
# Compile the model
model.compile(optimizer='adam', loss='mean_squared_error', metrics=['Accuracy'])

# Fit the model
model.fit(X_train, y_train, epochs=10)

Epoch 1/10
12/12 [==============================] - 0s 999us/step - loss: 462.8047 - Accuracy: 0.0000e+00
Epoch 2/10
12/12 [==============================] - 0s 913us/step - loss: 111.8643 - Accuracy: 0.0000e+00
Epoch 3/10
12/12 [==============================] - 0s 914us/step - loss: 37.9974 - Accuracy: 0.0027
Epoch 4/10
12/12 [==============================] - 0s 910us/step - loss: 34.1098 - Accuracy: 0.0027
Epoch 5/10
12/12 [==============================] - 0s 967us/step - loss: 30.5125 - Accuracy: 0.0027
Epoch 6/10
12/12 [==============================] - 0s 928us/step - loss: 26.7162 - Accuracy: 0.0027
Epoch 7/10
12/12 [==============================] - 0s 937us/step - loss: 24.7509 - Accuracy: 0.0027
Epoch 8/10
12/12 [==============================] - 0s 956us/step - loss: 23.5690 - Accuracy: 0.0027
Epoch 9/10
12/12 [==============================] - 0s 932us/step - loss: 23.0150 - Accuracy: 0.0027
Epoch 10/10
12/12 [==============================] - 0s 936us/step - loss: 22.3442 - Accuracy: 0.0027

## Predicting on test data

In [23]:
# Make predictions using the model
predictions = model.predict(X_test)

# Calculate mean squared error
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test, predictions)
mse

6/6 [==============================] - 0s 792us/step

23.942982089277862

# Applying keras model on classification problem

In [24]:
# Importing titanic dataset
titanic = pd.read_csv('datasets/titanic_all_numeric.csv')
titanic.head()

   survived  pclass  ...  embarked_from_queenstown  embarked_from_southampton
0         0       3  ...                         0                          1
1         1       1  ...                         0                          0
2         1       3  ...                         0                          1
3         1       1  ...                         0                          1
4         0       3  ...                         0                          1

[5 rows x 11 columns]

In [49]:
# Initializing features 
features = np.array(titanic.drop('survived',axis=1), dtype=np.float32)

# Initializing target : predicting survived or not
target = np.array(pd.get_dummies(titanic['survived']), dtype=np.float32)

In [52]:
# Train - test split
X_train_t, X_test_t, y_train_t, y_test_t = train_test_split(features, target,
                                                           test_size=0.3, random_state=42)

In [53]:
# No. of imput features
n_cols = features.shape[1]

In [54]:
n_cols

10

In [55]:
# Specify Architecture
model_classification = Sequential()

# First dense layer: 10 --> 16 nodes
model_classification.add(Dense(16, activation='relu', input_shape=(n_cols,)))

# Second dense layer: 16 --> 8 nodes
model_classification.add(Dense(8, activation='relu'))

# Output layer: 8 --> 2 nodes that classifies survived or not
model_classification.add(Dense(2, activation='softmax'))

In [59]:
# Model summary
model_classification.summary()

Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_18 (Dense)            (None, 16)                176

 dense_19 (Dense)            (None, 8)                 136

 dense_20 (Dense)            (None, 2)                 18

=================================================================
Total params: 330
Trainable params: 330
Non-trainable params: 0
_________________________________________________________________

In [56]:
# Compile the model
model_classification.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['Accuracy'])

# Fit the model
model_classification.fit(X_train_t, y_train_t, epochs=20)

Epoch 1/20
20/20 [==============================] - 0s 874us/step - loss: 1.9871 - Accuracy: 0.3917
Epoch 2/20
20/20 [==============================] - 0s 809us/step - loss: 1.0180 - Accuracy: 0.6404
Epoch 3/20
20/20 [==============================] - 0s 811us/step - loss: 0.7673 - Accuracy: 0.6533
Epoch 4/20
20/20 [==============================] - 0s 798us/step - loss: 0.6963 - Accuracy: 0.6661
Epoch 5/20
20/20 [==============================] - 0s 802us/step - loss: 0.6503 - Accuracy: 0.6774
Epoch 6/20
20/20 [==============================] - 0s 798us/step - loss: 0.6204 - Accuracy: 0.6902
Epoch 7/20
20/20 [==============================] - 0s 803us/step - loss: 0.6024 - Accuracy: 0.6934
Epoch 8/20
20/20 [==============================] - 0s 781us/step - loss: 0.5943 - Accuracy: 0.6902
Epoch 9/20
20/20 [==============================] - 0s 818us/step - loss: 0.5876 - Accuracy: 0.6838
Epoch 10/20
20/20 [==============================] - 0s 797us/step - loss: 0.5778 - Accuracy: 0.6934
Epoch 11/20
20/20 [==============================] - 0s 843us/step - loss: 0.5739 - Accuracy: 0.7014
Epoch 12/20
20/20 [==============================] - 0s 752us/step - loss: 0.5749 - Accuracy: 0.6870
Epoch 13/20
20/20 [==============================] - 0s 780us/step - loss: 0.5612 - Accuracy: 0.6998
Epoch 14/20
20/20 [==============================] - 0s 783us/step - loss: 0.5584 - Accuracy: 0.6950
Epoch 15/20
20/20 [==============================] - 0s 813us/step - loss: 0.5526 - Accuracy: 0.6998
Epoch 16/20
20/20 [==============================] - 0s 798us/step - loss: 0.5470 - Accuracy: 0.7063
Epoch 17/20
20/20 [==============================] - 0s 830us/step - loss: 0.5454 - Accuracy: 0.7207
Epoch 18/20
20/20 [==============================] - 0s 810us/step - loss: 0.5447 - Accuracy: 0.7127
Epoch 19/20
20/20 [==============================] - 0s 819us/step - loss: 0.5392 - Accuracy: 0.7127
Epoch 20/20
20/20 [==============================] - 0s 792us/step - loss: 0.5406 - Accuracy: 0.7207

In [63]:
# Predict via the model
pred = model_classification.predict(X_test_t)

# Binary prediction of either survived or not
binary_predictions = np.where(pred > 0.5, 1, 0)

9/9 [==============================] - 0s 795us/step

In [65]:
# Calculate accuracy of the model
from sklearn.metrics import accuracy_score

accuracy_score(y_test_t, binary_predictions)

0.75